[package]
name = "radio_datetime_analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dcf77_utils = "0.4.0"
npl_utils = "0.2.1"
radio_datetime_utils = "0.4.2"
